### ISSUE TITLE
Handle non UTF8 encoding / better error message

### ISSUE THREAD

**Issue by nekowinston** [nate-sys/muc#7]
Hi there :wave:

Nice tool! I noticed that my ZSH history file was `latin1` encoded for some reason, so the program crashed on `read_to_string`:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', src/hist_file.rs:7:51
```

After opening the file with vim and doing a quick `:set fenc=utf8` it worked flawlessly.
I don't know how common latin1 encoded histories are, so it's probably just fine to not use `unwrap()` here for a better error message.

**Comment by nthnd** [comment]
I've been getting complaints about this. Thanks for clarifying. Will look into it

**Comment by mrusme** [comment]
Just tried what @nekowinston suggested, but I ended up with another error:

```
~ RUST_BACKTRACE=full muc --file hist --count 10 --pretty
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/hist_file.rs:17:24
stack backtrace:
   0:     0x555fabbc3b40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h591808416c41e0db
   1:     0x555fabbdfc3e - core::fmt::write::h32120f18eb099fb0
   2:     0x555fabbc1675 - std::io::Write::write_fmt::h5120f968441dcf61
   3:     0x555fabbc51c3 - std::panicking::default_hook::{{closure}}::ha3b399c84dfd3950
   4:     0x555fabbc4eaf - std::panicking::default_hook::h23c1de61997507b7
   5:     0x555fabbc586a - std::panicking::rust_panic_with_hook::hf54f54e71167af35
   6:     0x555fabbc5721 - std::panicking::begin_panic_handler::{{closure}}::h507de2259e8e1ea3
   7:     0x555fabbc3fec - std::sys_common::backtrace::__rust_end_short_backtrace::h9db799e5e5917087
   8:     0x555fabbc5482 - rust_begin_unwind
   9:     0x555fabb52aa3 - core::panicking::panic_fmt::h597fac4e15471a4b
  10:     0x555fabb5296d - core::panicking::panic::h1f1b2313b7733f31
  11:     0x555fabb57210 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::haf14d96b9ef09f84
  12:     0x555fabb532d3 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h60582bc65aec2feb
  13:     0x555fabb5577d - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h13df09929e5f1463
  14:     0x555fabb57911 - muc::hist_file::parse_contents::h1c4553e5b8d7f473
  15:     0x555fabb5ec85 - muc::main::he849b2f82fabb51c
  16:     0x555fabb55e03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5673d428e6813b8f
  17:     0x555fabb57c19 - std::rt::lang_start::{{closure}}::hb2d23aad6cfc7fc4
  18:     0x555fabbbdfef - std::rt::lang_start_internal::h0b960bfca6f21183
  19:     0x555fabb62218 - main
  20:     0x7fe002ac734a - <unknown>
  21:     0x7fe002ac73fc - __libc_start_main
  22:     0x555fabb52c71 - _start
  23:                0x0 - <unknown>
```

**Comment by talwat** [comment]
This is probably the root cause of my issue (#3).

**Comment by nthnd** [comment]
There is now an option to display debug information. For now it only handles this case, but I'll solidify it more in the future

**Comment by nthnd** [comment]
> Just tried what @nekowinston suggested, but I ended up with another error:
> 
> ```
> ~ RUST_BACKTRACE=full muc --file hist --count 10 --pretty
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/hist_file.rs:17:24
> stack backtrace:
>    0:     0x555fabbc3b40 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h591808416c41e0db
>    1:     0x555fabbdfc3e - core::fmt::write::h32120f18eb099fb0
>    2:     0x555fabbc1675 - std::io::Write::write_fmt::h5120f968441dcf61
>    3:     0x555fabbc51c3 - std::panicking::default_hook::{{closure}}::ha3b399c84dfd3950
>    4:     0x555fabbc4eaf - std::panicking::default_hook::h23c1de61997507b7
>    5:     0x555fabbc586a - std::panicking::rust_panic_with_hook::hf54f54e71167af35
>    6:     0x555fabbc5721 - std::panicking::begin_panic_handler::{{closure}}::h507de2259e8e1ea3
>    7:     0x555fabbc3fec - std::sys_common::backtrace::__rust_end_short_backtrace::h9db799e5e5917087
>    8:     0x555fabbc5482 - rust_begin_unwind
>    9:     0x555fabb52aa3 - core::panicking::panic_fmt::h597fac4e15471a4b
>   10:     0x555fabb5296d - core::panicking::panic::h1f1b2313b7733f31
>   11:     0x555fabb57210 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::haf14d96b9ef09f84
>   12:     0x555fabb532d3 - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h60582bc65aec2feb
>   13:     0x555fabb5577d - <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h13df09929e5f1463
>   14:     0x555fabb57911 - muc::hist_file::parse_contents::h1c4553e5b8d7f473
>   15:     0x555fabb5ec85 - muc::main::he849b2f82fabb51c
>   16:     0x555fabb55e03 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5673d428e6813b8f
>   17:     0x555fabb57c19 - std::rt::lang_start::{{closure}}::hb2d23aad6cfc7fc4
>   18:     0x555fabbbdfef - std::rt::lang_start_internal::h0b960bfca6f21183
>   19:     0x555fabb62218 - main
>   20:     0x7fe002ac734a - <unknown>
>   21:     0x7fe002ac73fc - __libc_start_main
>   22:     0x555fabb52c71 - _start
>   23:                0x0 - <unknown>
> ```

 Have you tried running the latest version with the `--debug` option?
